config/routes.rb
Rails.application.routes.draw do

  root 'phase#index'
  get '/get_rendom_phase' => "phase#get_rendom_phase"
  get '/clear' => "phase#clear"

end

app/models/phase.rb
class Phase < ActiveRecord::Base

	def self.get_rand_id
		rand(1..10)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phase_controller.rb
class PhaseController < ApplicationController

	def index
		@phase = Phase.all
	end

	#get_rendom_phase_path
	def get_rendom_phase
		if (Phase.ids).all? { |e| session[:fetched_record].include?(e) }
			 @message = "No more element in DB!"
		else
			id  = unique_id(Phase.get_rand_id)
			@phase = Phase.find_by_id id
		end
	end

	def clear
		session[:fetched_record] = []
		redirect_to root_path
	end

	private
		def unique_id id 
			return if (Phase.ids).all? { |e| session[:fetched_record].include?(e) }
			if !(session[:fetched_record].include?(id)) && id > 0
				session[:fetched_record] << id
				return id
			else
				unique_id(Phase.get_rand_id)
			end

		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phase_helper.rb
module PhaseHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randomphase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/phase/_rand_phase_heading.html.erb
<% records =  session[:fetched_record] %>
<h1 class='text-center'>
	There are <%= (10-records.count) %> phrases left in the database.
</h1>

app/views/phase/_random_phase.html.erb
<% records = session[:fetched_record] %>
<%- records.each do |p| %>
	<div class="row" ">
		<div class="col-md-12 text-center" ">
			sample phrase number <%= p %>
		</div>
	</div>
<% end %>

app/views/phase/get_rendom_phase.js.erb
<% records = session[:fetched_record] %>	
	if (<%= (((Phase.ids).all? { |e| records.include?(e) })) || @message.present? %>){
		alert("No more element in DB!");
		$("#Phase-div").empty();
		$("#Phase-div").html("<%= escape_javascript(render partial: 'rand_phase_heading') %>");
		$("#Phase-div").append("<%= escape_javascript(render partial: 'random_phase') %>");
	}else{
		$("#Phase-div").empty();
		$("#Phase-div").html("<%= escape_javascript(render partial: 'rand_phase_heading') %>");
		$("#Phase-div").append("<%= escape_javascript(render partial: 'random_phase') %>");
	}
		

app/views/phase/index.html.erb
<div class="row">
	<div class="col-md-12 text-center">
		<%= link_to "Get new phase", get_rendom_phase_path, remote: true, class: "btn btn-primary mt-2 mb-2" %>	
	</div>
</div>
<div class="row ">
	<div class="col-md-12 text-center">
		<%= link_to "Clear phase", clear_path, class: "btn btn-danger mt-2"%>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="Phase-div">
		<h1 class="text-center"><%= render 'rand_phase_heading' %></h1>
		<div  class="text-center" "><%= render 'random_phase'%></div>
	</div>
</div>